### ISSUE TITLE
[question] Valid deploy mode

### ISSUE THREAD

**Issue by tisonkun** [dataArtisans/flink-benchmarks#6]
I wonder if these benchmarks only work with local mode, or we could modify and apply them on yarn cluster or other deploy environment.

**Comment by pnowojski** [comment]
Currently they work only for standalone mode on local machine, because maintaining cluster benchmarks is more complicate, requires quite a lot of more logic to automate them and resources/time to actually execute them.

But yes, we could modify them, add some yarn management logic to run them on yarn cluster and that would make them more valuable.

**Comment by tisonkun** [comment]
close as the discussion is over.
